(module test:test (layer F.Cu) (tedit 561B6A12) (tstamp <%= data.id %>)
    (at <%= data.x %> <%= data.y %> <%= data.rotation %>)
    (fp_text reference <%= data.name %> (at 0 1.925) (layer F.SilkS)
      (effects (font (size 0.8 0.8) (thickness 0.15)) (justify mirror))
    )
    (pad 1 smd rect (at -2.7 0) (size 2.5 0.5) (layers F.Cu)
      <%- data.netForPad(1) %>)
    (pad 2 smd rect (at 1.575 0) (size 1.2 1.2) (layers F.Cu F.Paste F.Mask)
      <%- data.netForPad(2) %>)
)
